name: Rss-feed-to-Blogger-action
description: Publish Rss feed posts As Posts in Blogger Website automatically
author: SSanjeevi
 
branding:
  icon: 'cast'  
  color: 'green'

inputs:
  GOOGLE_CREDENTIALS_Json:
    description: 'Google auth service account credentials json secret'
    required: true
  BloggerId:
    description: 'Blogger id'
    required: true
  RSSFeedUrl:
    description: 'Rss feed url to copy from content'
    required: true
  FeedArticleStartCount:
    description: 'Articles Start Count in the Feed'
    required: true
  FeedArticleEndCount:
    description: 'Articles End Count in the Feed'
    required: true
  Labels:
    description: 'List of string to be used as tags or labels for blog posts'
    required: false
  ApiKey:
    description: 'Google api key with blogger permission enabled'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-c"
    - ${{ inputs.GOOGLE_CREDENTIALS_Json }}
    - "-i"
    - ${{ inputs.BloggerId }}
    - "-l"
    - ${{ inputs.Labels }}
    - "-r"
    - ${{ inputs.RSSFeedUrl }}
    - "-s"
    - ${{ inputs.FeedArticleStartCount }}
    - "-e"
    - ${{ inputs.FeedArticleEndCount }}
    - "-k"
    - ${{ inputs.ApiKey }}
